sid-project/sid

rpm/sid.spec

The RPM spec file to build a package.
To test:
```sh
dnf copr enable galt/sid-project
```
```sh
dnf install sid
```

fix #18: add initial rpm spec file to pack SID.

---

rpm/sid.spec

The Copr build is failed because of missing file for debugsource package.
I disabled the build of debugsource.

rpm: disable debugsource subpackage building.

---

src/base/util.c
src/include/base/util.h
src/include/resource/ubridge-cmd-module.h
src/modules/ubridge-cmd/block/multipath_component/multipath_component.c
src/resource/ubridge.c
tests/Makefile.am
tests/test_bitmap.c
tests/test_buffer.c
tests/test_kv_store.c
tests/test_notify.c
tests/test_usid.c
udev/00-sid.rules.in

This updates the multipath component code to set the udev property to claim multipath devices.  It also updates the udev rules to make call usid on add events, and makes the multipath component respect the kernel cmdline multipath settings.

Make multipath_component claim devices

---

src/base/hash.c

When adding a new hash_node, hash_update_binary() finds the pointer that
will be set to point to that hash_node before calling _hash_update_fn(),
which calls the kv_update_fn. _kv_delta() can itself add hash_nodes to
the hash_table.  If these nodes are in the same slot as the one in the
original call to hash_update_binary(), they will set the same pointer
that was found in the original call. This means that when the original
hash_node is added, it will overwrite the pointer to the hash_nodes
added by _kv_delta() causing them to be lost, and memory to leak.
To fix this, _do_hash_insert_binary() now checks if the found pointer is
no longer NULL after the kv_update_fn is called, and if so, continues
down the list until if finds a NULL pointer. This will fix the issue,
assuming that the …

base: hash: fix lost hash_node because of _kv_delta

---

man/sid.8.in
src/daemon/sid.c
src/include/log/log.h
src/log/Makefile.am
src/log/log-target-journal.c
src/log/log.c

This is just a "work in progress" to see if you are interested in adding logging to the journal as an option.
I think it would be useful to add structure to the device specific messages.  For example adding IDs for block devices related to storage events would make monitoring specific devices easier.
Please let me know what you think...  FYI - this is an example of a journal entry:
{
"_SELINUX_CONTEXT" : "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
"_TRANSPORT" : "journal",
"_UID" : "0",
"_GID" : "0",
"_COMM" : "sid",
"_CAP_EFFECTIVE" : "ffffffffff",
"_BOOT_ID" : "d0a2df43b8d748daa238fb6cc495c959",
"_SYSTEMD_CGROUP" : "/user.slice/user-1000.slice/user@1000.service/apps.slice/apps-org.gnome.Terminal.slice/vte-spawn-14054f91-f531-4340-925c-5c327c264ebb.scope", …

Add option to output logs as structured data to the journal

---

src/daemon/sid.c
src/resource/resource.c
src/resource/sid.c
src/resource/worker-control.c
src/tools/usid/usid.c

A systemd process is required to use sd_event_add_signal() rather than
signal() to get notifications of process signals.
Updated to use existing sid_resource_create_signal_event_source() to
handle SIGINT and SIGTERM.
Signed-off-by: Todd Gill <tgill@redhat.com>

Update signal handling for systemd conventions

---

.clang-format
tests/test_bitmap.c
tests/test_buffer.c
tests/test_hash.c
tests/test_notify.c
tests/test_usid.c

`#include <cmocka.h>` in tests needs to go at the very end - looks like cmocka doesn't include its own dependencies.

Fix automatic formatting for #include <cmocka.h> in tests

---

.gitignore
src/tools/sidctl/sidctl.c

Note: also updated .gitignore with .vscode
The PR is the minimum to get JSON output for sidctl dump and version commands.
Example output for dump:
```
{
"siddb": [
{
"RECORD": 0,
"key": ":U:::::ID_FS_BOOT_SYSTEM_ID",
"seqnum": 0,
"KV_MOD_RESERVED": true,
"owner": "block/blkid",
"value": ""
},
{
"RECORD": 1,
"key": ":U:::::ID_FS_UUID_SUB_ENC",
"seqnum": 0,
"KV_MOD_RESERVED": true,
"owner": "block/blkid",
"value": ""
},
{
"RECORD": 2,
"key": ":U:::::ID_FS_LABEL_ENC",
"seqnum": 0,
"KV_MOD_RESERVED": true,
"owner": "block/blkid",
"value": ""
},
{
"RECORD": 3,
"key": ":U:::::ID_FS_UUID_SUB",
"seqnum": 0,
"KV_MOD_RESERVED": true,
"owner": "block/blkid",
"value": ""
},
{
"RECORD": 4,
"key": ":U:::::ID_PART_TABLE_UUID",
"seqnum": 0,
"KV_MOD_RESERVED": true,
"owner": "block/blkid",
"value": ""
}, …
```

sidctl: add json output for dump and version commands

---

src/resource/resource.c
src/resource/sid.c

Signal event handling through sd_event_add_signal() has special code to
deal with the fact that sd_event_add_child() may also be watching for
the SIGCHLD signal. If SIGCHLD is watched by the new SID signal event
code, it can get stuck in _sd_signal_event_handler() when a child exits.
Don't watch for SIGCHLD, to avoid interfering with sd_event_add_child().
Also, open the signalfd in non-blocking mode, as sd_event_add_signal()
does, to avoid the possibility of getting stuck in
_sd_signal_event_handler().

resource: Don't create a signal event for SIGCHLD

---

src/base/hash.c
src/include/base/hash.h
src/include/iface/usid.h
src/include/resource/kv-store.h
src/resource/kv-store.c
src/resource/ubridge.c
src/tools/sidctl/sidctl.c

Here is the sidctl stats command, and other minor cleanups. If you want different stats reported, just let met know.

Kv store stats

---

src/base/formatter.c
src/iface/usid.c
src/include/base/formatter.h
src/include/iface/usid.h
src/include/resource/ucmd-module.h
src/resource/ubridge.c
src/tools/sidctl/Makefile.am
src/tools/sidctl/sidctl.c
src/tools/usid/usid.c

This patchset makes _export_kv_store() use a memfd backed buffer, and uses the same code to build the kv dump for sidctl.

kv export code merge

---

BSD_LICENSE
rpm/sid.spec
src/base/Makefile.am
src/base/base64.c
src/base/buffer-type-linear.c
src/base/buffer-type-vector.c
src/base/buffer.c
src/base/formatter.c
src/include/base/base64.h
src/include/base/formatter.h
src/resource/ubridge.c
src/tools/sidctl/sidctl.c

This patchset adds support for dumping udev variables in sidctl, and printing binary dump data in base64 encoding. A number of the changes for encoding the base64 data are there to avoid mallocing memory for the encoded data, which would just be freed after writing it to the memfd buffer. If you don't care about the extra malloc for binary data, this patchset can get simplified.

Binary encode

---

src/include/resource/kv-store.h
src/resource/kv-store.c
src/resource/ubridge.c

Make `key` and `arg` parameters a part of existing `struct kv_store_update_spec` so all fields related to the KV record update are in one place, not passing them separately to each update function/subfunction.

minor kv cleanups

---

src/include/resource/kv-store.h
src/resource/kv-store.c
src/resource/ubridge.c
tests/test_kv_store.c

Most of the calls to kv_store_iter_next() subsequently call
kv_store_iter_current_key().  Update to return the key in the same call.
Signed-off-by: Todd Gill <tgill@redhat.com>

kv-store: optionally return the key with calls to kv_store_iter_next()

---

src/daemon/sid.c
src/include/resource/worker-control.h
src/resource/resource.c
src/resource/ubridge.c
src/resource/worker-control.c

This patchset makes the worker process clean up the inherited resources before starting up the worker event loop.
Resolves #85, Resolves #108

Worker cleanup

---

src/internal/bptree.c
src/internal/util.c
tests/Makefile.am
tests/test_bptree.c

Aside from fixing some bptree bugs, the main thing that this MR does is to remove the unnecessary temporary memory allocations when splitting nodes and leaves, and to make sure that the bptree code does all the necessary memory allocations before ever modifying the tree.  This means that the code can't error out once it starts modifying the tree.  The MR also adds bptree unit tests, to make sure that everything works as expected.

Bptree fixes and cleanups

---

src/base/buffer-type-linear.c
src/base/buffer-type-vector.c
src/base/buffer.c
src/include/base/buffer-type.h
src/include/base/buffer.h
src/include/resource/kv-store.h
src/resource/kv-store.c
src/resource/resource.c
src/resource/ubridge.c
tests/Makefile.am
tests/test_buffer.c
tests/test_db_sync.c
tests/test_kv_store.c

_sync_main_kv_store() can now rollback if it encounters a failure syncing the kv store. Since unsetting an entry cannot fail, it delays performing these actions until it has already performed the ones that can fail.  For actions that can fail (setting, adding and removing), the kv callbacks now have access to an opaque pointer to the current kv_store_value.  They save this value instead of destroying it. If all the the actions succeed, the saved values are destroyed.  Otherwise, the saved values are used to rollback to state of the database. The new value is destroyed and depending on whether the saved value was NULL or not, the entry is either removed, or it's value is replaced by the saved value. Neither of these actions can fail.  It is possible that the old value was saved, but the …

Add ability for kv store sync to rollback to previous state on failure.

---

.github/workflows/tests.yml

This will build SID and run 'make check' on PRs and when a commit is pushed to the main branch in a latest stable Fedora container.

ci: Add a simple GitHub action to run tests in Fedora container

---

Makefile.am
configure.ac
man/Makefile.am
man/sid.8.in
rpm/sid.spec
src/base/Makefile.am
src/iface/Makefile.am
src/modules/ucmd/type/dm/Makefile.am
systemd/Makefile.am

I am not really sure if all the autotools related changes are correct, but `make dist` and `rpmbuild` seems to be working now.

Various RPM build related fixes

---

src/iface/service-link.c
src/include/iface/service-link.h
src/modules/ucmd/type/dm/dm.c
src/resource/resource.c
src/resource/ubridge.c
tests/test_notify.c

I've gotten distracted with other things, so I haven't made much progress on the remove work yet, but here are some fixes that I've accumulated while looking through the code to understand what needs to be done.  I'm not quite sure if the final commit is the correct solution (erroring out instead of just skipping the failed sysfs attribute and going on). But the most likely cause of this seems to be that the sysfs device has disappeared. Right now this happens during remove events, but even when those have a different call path, the sysfs device could still get removed while we are processing an earlier uevent. in this case, I don't see much point in continuing to update the database for the device. But if you'd rather the code skip adding that attribute and continue with the function, I …

Misc cleanups

---

src/include/resource/ucmd-module.h
src/modules/ucmd/block/blkid/blkid.c
src/modules/ucmd/block/dm_mpath/dm_mpath.c
src/modules/ucmd/block/dummy_block/dummy_block.c
src/modules/ucmd/type/dm/dm.c
src/modules/ucmd/type/dm/lvm/lvm.c
src/modules/ucmd/type/dummy_type/dummy_type.c
src/resource/ubridge.c

I still keep having other things on my plate that are keeping me from being able to finish up the remove work. Instead, I'll just send you what I currently have, so you can see the direction I'm heading. I've split out the remove work from the regular scan work, although it still uses the "usid scan" command, since there is a lot of code overlap with regular scans. It currently doesn't do anything special on removes. That's what I'm working on next. Also, here are fixes for two bugs that were keeping resyncing the device hierarchy from working on removes.

More bugfixes and remove infrastructure
